version: '3'
services:
  sql-server:
    container_name: opsapp-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'P@ssw0rd'
      MSSQL_PID: Express
      MSSQL_LCID: 1041
      MSSQL_COLLATION: Japanese_CI_AS
    volumes:
      - "./containers/sql-server:/var/opt/mssql"
  opsapp:
    build: .
    depends_on:
      - sql-server
    ports:
      - 3000:3000
    links:
      - sql-server:sql-server
    environment:
      DATABASE_HOST: sql-server
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: P@ssw0rd
